@startuml

class Gesture {
  {abstract} int getGesture()
}

class StaticGesture {
  +StaticGesture()
  +StaticGesture(hand)
  -detectGestureOneHand()
  -detectGestureTwoHands()
  +getGesture()

  -hands
  -hand
  -handCount
  -strength
  -leftHand
  -count
}

class DynamicGesture {
  +DynamicGesture()
  +DynamicGesture(hand)
  +getGesture()

  -hands
  -hand
  -handCount
  -strength
  -leftHand
  -count
}

class Filter {
  +Filter()

  +filterMean()
}

class DetectionListener {
  +onInit()
  +onConnect()
  +onDisconnect()
  +onExit()
	+onFrame()
	+onFocusGained()
	+onFocusLost()
	+onDeviceChange()
	+onServiceConnect()
	+onServiceDisconnect()

  -numberOfPositions
  -rows
  -cols
  -historicSize
  -rowOrigin
  -colOrigin
  -positions
  -filter
  -image
  -initialized
  -previous
  -actual
}

class ModelHandler {
  +setMode(int)
  +execute(Gesture)
}

class Communicator {
  +sendData(int*)
}

class GestValidator {
  +isValid()
}

Gesture <|-- StaticGesture
Gesture <|-- DynamicGesture
ModelHandler *-- Communicator
ModelHandler *-- Filter
DetectionListener *-- ModelHandler
DetectionListener *-- GestValidator
DynamicGesture *-- Filter
@enduml
