@startuml

class StaticGestures {
  +StaticGestures()
  +~StaticGestures()
  +StaticGestures(hand)
  +StaticGesture getGesture()
  -StaticGesture detectGestureOneHand()
  -StaticGesture detectGestureTwoHands()


  -HandList hands
  -int handCount
}

class StaticGesture <<Enum>> {
  ERROR_SG
  GRAB_ONE_HAND

  ONE_FINGER_LEFT_HAND
  ...

  ONE_FINGER_RIGHT_HAND
  ...

  LEFT_ZERO_RIGHT_ZERO
  ...
}

class Filter {
  +Filter()

  +filterMean()
}

class DetectionListener {
  +DetectionListener()
  +onInit(Leap::Controller&)
  +onConnect(Leap::Controller&)
  +onDisconnect(Leap::Controller&)
  +onExit(Leap::Controller&)
	+onFrame(Leap::Controller&)
	+onFocusGained(Leap::Controller&)
	+onFocusLost(Leap::Controller&)
	+onDeviceChange(Leap::Controller&)
	+onServiceConnect(Leap::Controller&)
	+onServiceDisconnect(Leap::Controller&)

  -ModeHandler handler
  -GestValidator validator

  -int mode
  -bool selectingMode
}

class ModelHandler {
  +bool mode1(StaticGesture gesture)
  +bool mode2(StaticGesture gesture, Leap::GestureList gestures, Leap::FingerList fingers)

  -Communicator communicator
}

class Communicator {
  -WSADATA WSAData
  -SOCKET sock
  -SOCKET csock
  -SOCKADDR_IN sin
  -SOCKADDR_IN csin
  -int sinsize

  +Communicator()
  +~Communicator()
  +sendData(char*)
}

class GestValidator {
  +GestValidator() :currentGesture(ERROR_SG), count(0), frameLimit(10) {}
	+~GestValidator() {}

	+void setFrameLimit(int limit)
	+int getFrameLimit()
	+void setGesture(StaticGesture gesture)
  +void update(StaticGesture gesture)
  +StaticGesture getCurrentValidGesture()

  -int count
  -int frameLimit
  -StaticGesture currentGesture
}

ModelHandler *-- Communicator
ModelHandler *-- Filter
DetectionListener *-- ModelHandler
DetectionListener *-- GestValidator
GestValidator *-- StaticGesture

hide StaticGesture methods
@enduml
